### ISSUE TITLE
Institution logos fail to load

### ISSUE THREAD

**Issue by JonathanOppenheimer** [ErikBoesen/seniormap#45]
Unsure of why this occurs -- incorrectly typed within spreadsheet maybe? Examples included below 
![c3](https://user-images.githubusercontent.com/12973114/111243580-aead7c00-85d7-11eb-9b2d-8e99f627ec78.PNG)
![c2](https://user-images.githubusercontent.com/12973114/111243581-aead7c00-85d7-11eb-8d64-d14f61d1bf79.PNG)
![c1](https://user-images.githubusercontent.com/12973114/111243582-aead7c00-85d7-11eb-8a6a-7dfcb59a2b12.PNG)

**Comment by ErikBoesen** [comment]
It's because the links to the images are simply gone from the links they were previously present at. For example, the GMU logo: https://brand.gmu.edu/wp-content/uploads/assets/primarylogo/PC/GMURGB.jpg

Another thing to consider (this isn't an issue with any of the images in your screenshots, but just for thinking down the line) is that if you're on an HTTPS page, you can't load resources over HTTP. So any HTTP linked images will fail to load even if they exist.

**Comment by JonathanOppenheimer** [comment]
incredibly large brain thank you sir -- I can go through the spreadsheet and replace the broken links and if they ever pop up again, ill know what to do. good thinking on HTTPS too -- site is def https so ill ensure only https image links are used
